### ISSUE TITLE
editorSimpleWorker.js: "the request of a dependency is an expression"

### ISSUE THREAD

**Issue by OneCyrus** [Microsoft/monaco-editor-webpack-plugin#13] opened 2018-05-19 13:28 UTC
i have multiple times this warning when building. any idea what causes this?

```WARNING in ./node_modules/monaco-editor/esm/vs/editor/common/services/editorSimpleWorker.js
388:12-397:17 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/monaco-editor/esm/vs/editor/common/services/editorSimpleWorker.js
 @ ./node_modules/monaco-editor/esm/vs/editor/common/services/editorWorkerServiceImpl.js
 @ ./node_modules/monaco-editor/esm/vs/editor/common/services/webWorker.js
 @ ./node_modules/monaco-editor/esm/vs/editor/standalone/browser/standaloneEditor.js
 @ ./node_modules/monaco-editor/esm/vs/editor/editor.api.js
 @ include-loader!./node_modules/monaco-editor/esm/vs/editor/editor.api.js
 @ ./node_modules/monaco-editor/esm/vs/language/typescript/monaco.contribution.js
 @ include-loader!./node_modules/monaco-editor/esm/vs/editor/editor.main.js
 @ ./node_modules/react-monaco-editor/lib/editor.js
 @ ./node_modules/react-monaco-editor/lib/index.js
 @ ./Scripts/network/NetworkEditorServices.tsx
 @ ./Scripts/network/networkadmin.tsx
 @ multi (webpack)-dev-server/client?http://localhost:35280 webpack/hot/dev-server ./Scripts/network/networkadmin.tsx```

**Comment by kqadem** [comment] 2018-05-21 22:51
Hi, 
had the same Issues. This solved it:
```js
new webpack.ContextReplacementPlugin(
	/monaco-editor(\\|\/)esm(\\|\/)vs(\\|\/)editor(\\|\/)common(\\|\/)services/,
	__dirname
)
```
I think the problem is somewhere in the weird `winjs.base.js ` file. Did not track it further. Still trying to figure out what is happening there with all those `WinJS/Core/_Global` voodoo....

**Comment by OneCyrus** [comment] 2018-05-22 19:01
that worked to suppress the error. but it seems like there are way too many hacks needed to get manoc running in a esm world. for now we replaced monaco with codemirror. will have a look again once the integration improves.

**Comment by alexandrudima** [comment] 2018-07-03 10:47
Duplicate of #3

**Closed by alexandrudima** 2018-07-03 10:47 UTC
